# config.mk
#
# Product-specific compile-time definitions.
#

# Inherit from OPPO common
-include device/oppo/common/BoardConfigCommon.mk

TARGET_OTA_ASSERT_DEVICE := OnePlus5,oneplus5,op5,A5001,A5003,A5005

PLATFORM_PATH := device/oneplus/oneplus5

# Optimizations
POLLY_OPTS := true
LOCAL_CLANG_LTO := true
TARGET_MORE_OPTIMIZATION := true

# Use Snapdragon LLVM, if available
TARGET_USE_SDCLANG := true

BOARD_VENDOR := oneplus
BOARD_USES_QCOM_HARDWARE := true

TARGET_BOARD_PLATFORM := msm8998
TARGET_BOOTLOADER_BOARD_NAME := MSM8998

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a9

# SDClang configuration
SDCLANG := true

TARGET_NO_BOOTLOADER := false
#TARGET_USES_UEFI := true
TARGET_NO_KERNEL := false

-include $(QCPATH)/common/msm8998/BoardConfigVendor.mk

# Some framework code requires this to enable BT
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true
BOARD_USES_WIPOWER := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/qcom/common

USE_OPENGL_RENDERER := true
BOARD_USE_LEGACY_UI := true

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x04000000

TARGET_NO_RECOVERY := true

BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_USERDATAIMAGE_PARTITION_SIZE := 10737418240
BOARD_PERSISTIMAGE_PARTITION_SIZE := 33554432
BOARD_PERSISTIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)

HWUI_COMPILE_FOR_PERF := true

TARGET_USES_ION := true
TARGET_USES_NEW_ION_API :=true
TARGET_USES_QCOM_BSP := true
TARGET_USES_COLOR_METADATA := true

BOARD_KERNEL_CMDLINE := \
        androidboot.hardware=qcom \
        ehci-hcd.park=3 \
        lpm_levels.sleep_disabled=1 \
        sched_enable_hmp=1 \
        sched_enable_power_aware=1 \
        service_locator.enable=1 \
        swiotlb=2048 \
        androidboot.configfs=true \
        androidboot.usbcontroller=a800000.dwc3

BOARD_EGL_CFG := $(PLATFORM_PATH)/egl.cfg

BOARD_KERNEL_BASE        := 0x00000000
BOARD_KERNEL_PAGESIZE    := 4096
BOARD_KERNEL_TAGS_OFFSET := 0x01E00000
BOARD_KERNEL_IMAGE_NAME  := Image.gz-dtb
BOARD_RAMDISK_OFFSET     := 0x02000000
TARGET_KERNEL_APPEND_DTB := true
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_SOURCE := kernel/oneplus/msm8998
TARGET_KERNEL_CONFIG := oneplus5_defconfig
TARGET_FRESHLY_COMPILED_DTBTOOL := true
TARGET_KERNEL_BUILD_VARIANT := user

# Link Toolchain
TARGET_GCC_VERSION := 4.9
TARGET_GCC_VERSION_EXP := 4.9
TARGET_GCC_VERSION_EXP_ARM64 := $(TARGET_GCC_VERSION)
TARGET_GCC_VERSION_ARM64 := 4.9
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
TARGET_CROSS_COMPILE_PREFIX := aarch64-linux-android-
KERNEL_TOOLCHAIN := $(realpath $(TOP))/prebuilts/gcc/$(strip $(HOST_OS))-x86/aarch64/$(TARGET_CROSS_COMPILE_PREFIX)$(TARGET_GCC_VERSION_ARM64)/bin
TARGET_TOOLCHAIN_ROOT := prebuilts/gcc/$(strip $(HOST_OS))-x86/aarch64/$(TARGET_CROSS_COMPILE_PREFIX)$(TARGET_GCC_VERSION_EXP_ARM64)
TARGET_TOOLS_PREFIX := $(TARGET_TOOLCHAIN_ROOT)/bin/$(TARGET_CROSS_COMPILE_PREFIX)
TARGET_USES_UNCOMPRESSED_KERNEL := false

MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024

TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
MAX_VIRTUAL_DISPLAY_DIMENSION := 4096

VSYNC_EVENT_PHASE_OFFSET_NS := 0
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 0

TARGET_BOARD_PLATFORM_GPU := qcom-adreno540
HAVE_ADRENO_SOURCE := false
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so

BOARD_USES_GENERIC_AUDIO := true
BOARD_QTI_CAMERA_32BIT_ONLY := true
TARGET_NO_RPC := true

AUDIO_FINE_TUNED_OPTIMIZATIONS := true

USE_OPENGL_RENDERER := true

TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/
TARGET_INIT_VENDOR_LIB := libinit_msm

TARGET_INIT_COLDBOOT_TIMEOUT := 8

TARGET_BOOTANIMATION_MULTITHREAD_DECODE := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true

NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_KERNEL_APPEND_DTB := true
TARGET_COMPILE_WITH_MSM_KERNEL := true

#Enable HW based full disk encryption
TARGET_HW_DISK_ENCRYPTION := false

TARGET_CRYPTFS_HW_PATH := device/qcom/common/cryptfs_hw

TARGET_FORCE_DEXPREOPT ?= false
WITH_DEXPREOPT := $(TARGET_FORCE_DEXPREOPT)

TARGET_RIL_VARIANT := caf

#Enable peripheral manager
TARGET_PER_MGR_ENABLED := true

#Enable SSC Feature
TARGET_USES_SSC := true

# Enable sensor multi HAL
USE_SENSOR_MULTI_HAL := true

#Enable CPUSets
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true

# Audio
AUDIO_FEATURE_ENABLED_ACDB_LICENSE := true
AUDIO_FEATURE_ENABLED_COMPRESS_CAPTURE := true
AUDIO_FEATURE_ENABLED_COMPRESS_VOIP := true
AUDIO_FEATURE_ENABLED_DS2_DOLBY_DAP := true
AUDIO_FEATURE_ENABLED_EXTN_FORMATS := true
AUDIO_FEATURE_ENABLED_FLUENCE := true
AUDIO_FEATURE_ENABLED_HFP := true
AUDIO_FEATURE_ENABLED_INCALL_MUSIC := false
AUDIO_FEATURE_ENABLED_KPI_OPTIMIZE := false
AUDIO_FEATURE_ENABLED_MULTI_VOICE_SESSIONS := true
AUDIO_FEATURE_ENABLED_PROXY_DEVICE := true
AUDIO_FEATURE_ENABLED_PCM_OFFLOAD := true
AUDIO_FEATURE_ENABLED_PCM_OFFLOAD_24 := true
AUDIO_FEATURE_ENABLED_CUSTOMSTEREO := true
AUDIO_FEATURE_ENABLED_MULTIPLE_TUNNEL := true

AUDIO_FINE_TUNED_OPTIMIZATIONS := true

BOARD_HAL_STATIC_LIBRARIES := libhealthd.msm

#Enabling IMS Feature
TARGET_USES_IMS := true

-include vendor/oneplus/oneplus5/BoardConfigVendor.mk
